# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=400)),
                ('speech_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Play'),
        ),
        migrations.AddField(
            model_name='line',
            name='speaker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Speaker'),
        ),
    ]
