# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='play_id',
            new_name='play',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='speaker_id',
            new_name='speaker',
        ),
    ]
