# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161220_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
