# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161220_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='speech_no',
            field=models.IntegerField(null=True),
        ),
    ]
